FROM golang:1.24-alpine

WORKDIR /app

RUN apk add --no-cache bash git ca-certificates make curl unzip

ARG PROTOC_VERSION=28.3
RUN ARCH=$(uname -m | sed 's/aarch64/aarch_64/') && \
    curl -sSL "https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/protoc-${PROTOC_VERSION}-linux-${ARCH}.zip" \
    -o /tmp/protoc.zip && \
    unzip /tmp/protoc.zip -d /usr/local && \
    rm /tmp/protoc.zip

ARG ATLAS_VERSION=v0.36.2
RUN ATLAS_VERSION=${ATLAS_VERSION} curl -sSf https://atlasgo.sh | sh

RUN go install github.com/go-delve/delve/cmd/dlv@v1.26.3 && \
    go install github.com/githubnemo/CompileDaemon@v1.4.0 && \
    go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.27.2 && \
    go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v2.27.2 && \
    go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.9 && \
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1

EXPOSE 50050 50051 2302
