// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.28.3
// source: apis.proto

package pb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_apis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_apis_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_apis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_apis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_apis_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_apis_proto protoreflect.FileDescriptor

const file_apis_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"apis.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\rproduct.proto\x1a\x1bbuf/validate/validate.proto\"*\n" +
	"\fHelloRequest\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xeb\x02\n" +
	"\x03API\x12O\n" +
	"\vHealthCheck\x12\x16.google.protobuf.Empty\x1a\x0e.pb.HelloReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/health-check\x12F\n" +
	"\bSayHello\x12\x10.pb.HelloRequest\x1a\x0e.pb.HelloReply\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/say-hello\x12r\n" +
	"\x12CreateManyProducts\x12\x1d.pb.CreateManyProductsRequest\x1a\x1e.pb.CreateManyProductsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/products/batch\x12W\n" +
	"\fListProducts\x12\x17.pb.ListProductsRequest\x1a\x18.pb.ListProductsResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/v1/productsB0Z.github.com/dangngochoainam/codebase-go-grpc/pbb\x06proto3"

var (
	file_apis_proto_rawDescOnce sync.Once
	file_apis_proto_rawDescData []byte
)

func file_apis_proto_rawDescGZIP() []byte {
	file_apis_proto_rawDescOnce.Do(func() {
		file_apis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apis_proto_rawDesc), len(file_apis_proto_rawDesc)))
	})
	return file_apis_proto_rawDescData
}

var file_apis_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_apis_proto_goTypes = []any{
	(*HelloRequest)(nil),               // 0: pb.HelloRequest
	(*HelloReply)(nil),                 // 1: pb.HelloReply
	(*emptypb.Empty)(nil),              // 2: google.protobuf.Empty
	(*CreateManyProductsRequest)(nil),  // 3: pb.CreateManyProductsRequest
	(*ListProductsRequest)(nil),        // 4: pb.ListProductsRequest
	(*CreateManyProductsResponse)(nil), // 5: pb.CreateManyProductsResponse
	(*ListProductsResponse)(nil),       // 6: pb.ListProductsResponse
}
var file_apis_proto_depIdxs = []int32{
	2, // 0: pb.API.HealthCheck:input_type -> google.protobuf.Empty
	0, // 1: pb.API.SayHello:input_type -> pb.HelloRequest
	3, // 2: pb.API.CreateManyProducts:input_type -> pb.CreateManyProductsRequest
	4, // 3: pb.API.ListProducts:input_type -> pb.ListProductsRequest
	1, // 4: pb.API.HealthCheck:output_type -> pb.HelloReply
	1, // 5: pb.API.SayHello:output_type -> pb.HelloReply
	5, // 6: pb.API.CreateManyProducts:output_type -> pb.CreateManyProductsResponse
	6, // 7: pb.API.ListProducts:output_type -> pb.ListProductsResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apis_proto_init() }
func file_apis_proto_init() {
	if File_apis_proto != nil {
		return
	}
	file_product_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apis_proto_rawDesc), len(file_apis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apis_proto_goTypes,
		DependencyIndexes: file_apis_proto_depIdxs,
		MessageInfos:      file_apis_proto_msgTypes,
	}.Build()
	File_apis_proto = out.File
	file_apis_proto_goTypes = nil
	file_apis_proto_depIdxs = nil
}
