// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.28.3
// source: product.proto

package pb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductItem) Reset() {
	*x = ProductItem{}
	mi := &file_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductItem) ProtoMessage() {}

func (x *ProductItem) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductItem.ProtoReflect.Descriptor instead.
func (*ProductItem) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{0}
}

func (x *ProductItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductItem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ProductItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductItem) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type CreateManyProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductItem         `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateManyProductsRequest) Reset() {
	*x = CreateManyProductsRequest{}
	mi := &file_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateManyProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateManyProductsRequest) ProtoMessage() {}

func (x *CreateManyProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateManyProductsRequest.ProtoReflect.Descriptor instead.
func (*CreateManyProductsRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{1}
}

func (x *CreateManyProductsRequest) GetProducts() []*ProductItem {
	if x != nil {
		return x.Products
	}
	return nil
}

type ProductDetail struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code           string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Price          float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Image          string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastModifiedAt string                 `protobuf:"bytes,7,opt,name=last_modified_at,json=lastModifiedAt,proto3" json:"last_modified_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProductDetail) Reset() {
	*x = ProductDetail{}
	mi := &file_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductDetail) ProtoMessage() {}

func (x *ProductDetail) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductDetail.ProtoReflect.Descriptor instead.
func (*ProductDetail) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{2}
}

func (x *ProductDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductDetail) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ProductDetail) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductDetail) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ProductDetail) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ProductDetail) GetLastModifiedAt() string {
	if x != nil {
		return x.LastModifiedAt
	}
	return ""
}

type CreateManyProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	StatusCode    string                 `protobuf:"bytes,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ReasonCode    string                 `protobuf:"bytes,3,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	ReasonMessage string                 `protobuf:"bytes,4,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	TimeMs        float64                `protobuf:"fixed64,5,opt,name=time_ms,json=timeMs,proto3" json:"time_ms,omitempty"`
	Products      []*ProductDetail       `protobuf:"bytes,6,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateManyProductsResponse) Reset() {
	*x = CreateManyProductsResponse{}
	mi := &file_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateManyProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateManyProductsResponse) ProtoMessage() {}

func (x *CreateManyProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateManyProductsResponse.ProtoReflect.Descriptor instead.
func (*CreateManyProductsResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{3}
}

func (x *CreateManyProductsResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *CreateManyProductsResponse) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *CreateManyProductsResponse) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *CreateManyProductsResponse) GetReasonMessage() string {
	if x != nil {
		return x.ReasonMessage
	}
	return ""
}

func (x *CreateManyProductsResponse) GetTimeMs() float64 {
	if x != nil {
		return x.TimeMs
	}
	return 0
}

func (x *CreateManyProductsResponse) GetProducts() []*ProductDetail {
	if x != nil {
		return x.Products
	}
	return nil
}

type ListProductsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Limit int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Opaque cursor from the previous response's next_cursor field.
	// Omit (or send empty) to fetch the first page.
	After string `protobuf:"bytes,2,opt,name=after,proto3" json:"after,omitempty"`
	// Field to sort by. Supported values: "created_at" (default), "name".
	SortBy string `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	// Sort direction. Supported values: "asc", "desc" (default).
	SortOrder     string `protobuf:"bytes,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{4}
}

func (x *ListProductsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListProductsRequest) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

func (x *ListProductsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListProductsRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

// KeysetPagination is the pagination envelope returned on every list response.
// has_next tells the caller whether more pages exist.
// next_cursor must be passed as `after` on the next request; it is opaque — never parse it.
type KeysetPagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasNext       bool                   `protobuf:"varint,1,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeysetPagination) Reset() {
	*x = KeysetPagination{}
	mi := &file_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeysetPagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeysetPagination) ProtoMessage() {}

func (x *KeysetPagination) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeysetPagination.ProtoReflect.Descriptor instead.
func (*KeysetPagination) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{5}
}

func (x *KeysetPagination) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

func (x *KeysetPagination) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	StatusCode    string                 `protobuf:"bytes,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ReasonCode    string                 `protobuf:"bytes,3,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	ReasonMessage string                 `protobuf:"bytes,4,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	TimeMs        float64                `protobuf:"fixed64,5,opt,name=time_ms,json=timeMs,proto3" json:"time_ms,omitempty"`
	Products      []*ProductDetail       `protobuf:"bytes,6,rep,name=products,proto3" json:"products,omitempty"`
	Pagination    *KeysetPagination      `protobuf:"bytes,7,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{6}
}

func (x *ListProductsResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ListProductsResponse) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *ListProductsResponse) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *ListProductsResponse) GetReasonMessage() string {
	if x != nil {
		return x.ReasonMessage
	}
	return ""
}

func (x *ListProductsResponse) GetTimeMs() float64 {
	if x != nil {
		return x.TimeMs
	}
	return 0
}

func (x *ListProductsResponse) GetProducts() []*ProductDetail {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsResponse) GetPagination() *KeysetPagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_product_proto protoreflect.FileDescriptor

const file_product_proto_rawDesc = "" +
	"\n" +
	"\rproduct.proto\x12\x02pb\x1a\x1bbuf/validate/validate.proto\"q\n" +
	"\vProductItem\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12\x1a\n" +
	"\x04code\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04code\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\"R\n" +
	"\x19CreateManyProductsRequest\x125\n" +
	"\bproducts\x18\x01 \x03(\v2\x0f.pb.ProductItemB\b\xbaH\x05\x92\x01\x02\b\x01R\bproducts\"\xbc\x01\n" +
	"\rProductDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12(\n" +
	"\x10last_modified_at\x18\a \x01(\tR\x0elastModifiedAt\"\xe8\x01\n" +
	"\x1aCreateManyProductsResponse\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\tR\n" +
	"statusCode\x12\x1f\n" +
	"\vreason_code\x18\x03 \x01(\tR\n" +
	"reasonCode\x12%\n" +
	"\x0ereason_message\x18\x04 \x01(\tR\rreasonMessage\x12\x17\n" +
	"\atime_ms\x18\x05 \x01(\x01R\x06timeMs\x12-\n" +
	"\bproducts\x18\x06 \x03(\v2\x11.pb.ProductDetailR\bproducts\"\x84\x01\n" +
	"\x13ListProductsRequest\x12\x1f\n" +
	"\x05limit\x18\x01 \x01(\x05B\t\xbaH\x06\x1a\x04\x18d(\x01R\x05limit\x12\x14\n" +
	"\x05after\x18\x02 \x01(\tR\x05after\x12\x17\n" +
	"\asort_by\x18\x03 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\tR\tsortOrder\"N\n" +
	"\x10KeysetPagination\x12\x19\n" +
	"\bhas_next\x18\x01 \x01(\bR\ahasNext\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"\x98\x02\n" +
	"\x14ListProductsResponse\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\tR\n" +
	"statusCode\x12\x1f\n" +
	"\vreason_code\x18\x03 \x01(\tR\n" +
	"reasonCode\x12%\n" +
	"\x0ereason_message\x18\x04 \x01(\tR\rreasonMessage\x12\x17\n" +
	"\atime_ms\x18\x05 \x01(\x01R\x06timeMs\x12-\n" +
	"\bproducts\x18\x06 \x03(\v2\x11.pb.ProductDetailR\bproducts\x124\n" +
	"\n" +
	"pagination\x18\a \x01(\v2\x14.pb.KeysetPaginationR\n" +
	"paginationB0Z.github.com/dangngochoainam/codebase-go-grpc/pbb\x06proto3"

var (
	file_product_proto_rawDescOnce sync.Once
	file_product_proto_rawDescData []byte
)

func file_product_proto_rawDescGZIP() []byte {
	file_product_proto_rawDescOnce.Do(func() {
		file_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)))
	})
	return file_product_proto_rawDescData
}

var file_product_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_product_proto_goTypes = []any{
	(*ProductItem)(nil),                // 0: pb.ProductItem
	(*CreateManyProductsRequest)(nil),  // 1: pb.CreateManyProductsRequest
	(*ProductDetail)(nil),              // 2: pb.ProductDetail
	(*CreateManyProductsResponse)(nil), // 3: pb.CreateManyProductsResponse
	(*ListProductsRequest)(nil),        // 4: pb.ListProductsRequest
	(*KeysetPagination)(nil),           // 5: pb.KeysetPagination
	(*ListProductsResponse)(nil),       // 6: pb.ListProductsResponse
}
var file_product_proto_depIdxs = []int32{
	0, // 0: pb.CreateManyProductsRequest.products:type_name -> pb.ProductItem
	2, // 1: pb.CreateManyProductsResponse.products:type_name -> pb.ProductDetail
	2, // 2: pb.ListProductsResponse.products:type_name -> pb.ProductDetail
	5, // 3: pb.ListProductsResponse.pagination:type_name -> pb.KeysetPagination
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_product_proto_init() }
func file_product_proto_init() {
	if File_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_product_proto_goTypes,
		DependencyIndexes: file_product_proto_depIdxs,
		MessageInfos:      file_product_proto_msgTypes,
	}.Build()
	File_product_proto = out.File
	file_product_proto_goTypes = nil
	file_product_proto_depIdxs = nil
}
